// get all users
GET http://localhost:5000/users

#############################################

// get 1 users
GET http://localhost:5000/users/1

#############################################

// create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "nama": "niam",
    "email": "niam@gmail.com",
    "gender": "male"
}
#############################################

// update user
PATCH  http://localhost:5000/users/2
Content-Type: application/json

{
    "nama": "niam updated",
    "email": "niam@gmail.com",
    "gender": "male"
}
#############################################